version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine
    volumes:
      - ./front_envoy/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "3000:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'front-envoy' --service-node 'front-envoy' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"
    networks: 
      - diegox

  # service_a_envoy:
  #   image: envoyproxy/envoy-alpine
  #   volumes:
  #     - ./service_a/envoy-config.yaml:/etc/envoy-config.yaml
  #   ports:
  #     - "3006:3006"
  #     - "3007:3007"
  #     - "3008:3008"
  #   command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-a' --service-node 'service-a' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"

  # service_a:
  #   build: service_a/
  #   ports:
  #   - "3005:80"

  service_b_envoy:
    image: envoyproxy/envoy-alpine
    volumes:
      - ./service_b/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "3011:3011"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-b' --service-node 'service-b' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  
    networks: 
      - diegox

  service_b:
    build: service_b/
    ports:
    - "3010:3010"
    networks: 
      - diegox

  service_c_envoy:
    image: envoyproxy/envoy-alpine
    volumes:
      - ./service_c/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "3016:3016"
      - "3017:3017"
      - "3018:3018"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-c' --service-node 'service-c' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  
    networks: 
      - diegox

  service_c:
    build: service_c/
    ports:
    - "3015:3015"  
    networks: 
      - diegox

  service_d_envoy:
    image: envoyproxy/envoy-alpine
    volumes:
      - ./service_d/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "3021:3021"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml -l info --service-cluster 'service-d' --service-node 'service-d' --log-format '[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"  
    networks: 
      - diegox

  service_d:
    build: service_d/
    ports:
    - "3020:3020"  
    networks: 
      - diegox

networks: 
    diegox:
      external: true
  